name: Build and Publish Uber JAR

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: temurin
          java-version: 8

      - name: Build and Test
        run: sbt -v +test

      - name: Build Uber JAR
        run: sbt assembly

      - name: Publish Uber JAR
        uses: actions/upload-artifact@v2
        with:
          name: spark-pinecone-uber-jar.jar
          path: spark-pinecone/target/scala-*/spark-pinecone-*.jar