name: Build and Publish Uber JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: temurin
          java-version: 8

      # - name: Build and Test
      #   run: sbt -v +test

      - name: Build Uber JAR
        run: sbt assembly

      - name: Get Version
        id: version
        run: echo ::set-output name=snapshot::$(sbt -no-colors 'print version' | tail -n 1)

      - name: Show Version
        run: echo $(sbt -no-colors 'print version' | tail -n 1)

      - name: Output Version
        run: echo "JAR_VERSION=${{ steps.version.outputs.snapshot }}" >> $GITHUB_ENV

      - name: Upload Uber JAR
        uses: actions/upload-artifact@v3
        with:
          name: spark-pinecone-uber-jar
          path: target/scala-2.12/*.jar

